blog/urls.py
from django.urls import path
from django.urls.base import reverse_lazy
from . import views

app_name = "blog"
urlpatterns = [
    path('', views.blog_home, name="blog_home"),

    # Posts CRUD
    path('list/', views.PostListView.as_view(), name="post_list"),
    path('post/create/', views.PostCreateView.as_view(success_url=reverse_lazy(f'{app_name}:post_list')), name="post_create"),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name="post_detail"),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name="post_update"),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(success_url=reverse_lazy(f'{app_name}:post_list')), name="post_delete"),

    # Comments CRUD
    path('post/<int:pk>/create_comment/', views.CommentCreateView.as_view(success_url=reverse_lazy(f'{app_name}:post_list')), name="comment_create"),
    path('comment/<int:pk>/', views.CommentDetailView.as_view(), name="comment_detail"),
    path('comment/<int:pk>/update/', views.CommentUpdateView.as_view(), name="comment_update"),
    path('comment/<int:pk>/delete/', views.CommentDeleteView.as_view(success_url=reverse_lazy(f'{app_name}:post_list')), name="comment_delete"),
]

resumes/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy

from . import views


from django.views.decorators.cache import cache_page

app_name = "resumes"
# cache_page(60*15)(view)

urlpatterns = [

    path('', cache_page(60*15, key_prefix="resume_list")(views.home), name="home"),

    # Resumes CRUD
    # path('list/', (views.ResumeListView.as_view()), name="resume_list"),
    path('list/', views.ResumeListView.as_view(), name="resume_list"),
    path('user/<str:username>/', views.UserResumeListView.as_view(), name="user_resumes"),
    path('resume/create/', views.ResumeCreateView.as_view(success_url=reverse_lazy(f'{app_name}:resume_list')), name="resume_create"),
    path('resume/<int:pk>/', views.ResumeDetailView.as_view(), name="resume_detail"),
    path('resume/<int:pk>/update/', views.ResumeUpdateView.as_view(), name="resume_update"),
    path('resume/<int:pk>/delete/', views.ResumeDeleteView.as_view(success_url=reverse_lazy(f'{app_name}:resume_list')), name="resume_delete"),

    # ! path('resume/list/<int:pk>/', views.GetResume, name="get_resume"),

    # Reviews CRUD
    path('review/list/', views.ReviewListView.as_view(), name="review_list"),
    path('user/reviews/<str:username>/', views.UserReviewListView.as_view(), name="user_reviews"),
    path('resume/<int:pk>/create_review/', views.ReviewCreateView.as_view(), name="review_create"),
    path('review/<int:pk>/', views.ReviewDetailView.as_view(), name="review_detail"),
    path('review/<int:pk>/update/', views.ReviewUpdateView.as_view(), name="review_update"),
    path('review/<int:pk>/delete/', views.ReviewDeleteView.as_view(success_url=reverse_lazy(f'{app_name}:resume_list')), name="review_delete"),
]

blog/models.py
from django.db import models
from django.urls.base import reverse
from django.utils import timezone
from django.conf import settings
# Create your models here.


class PostQuerySet(models.QuerySet):
    def approve(self):
        """Approve one Post instance. Notice: work on the QuerySet not on a model instance"""
        return self.update(status=Post.STATUS_APPROVED)

    def bulk_approve(self):
        """Approve bulk of Post instances."""
        for obj in self:
            obj.status = Post.STATUS_APPROVED
        return self.bulk_update(self, ['status'])


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField(default="")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    STATUS_DRAFT, STATUS_APPROVED = False, True
    STATUS_CHOICES = (
        (STATUS_DRAFT, 'Draft'),
        (STATUS_APPROVED, 'Approved')
    )
    status = models.BooleanField(choices=STATUS_CHOICES, default=STATUS_DRAFT)

    objects = PostQuerySet.as_manager()

    def __str__(self):
        return f'{self.title}'

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.pk})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f'comment of {self.author} on "{self.post}" post'

blog/forms.py
from django import forms
from .models import Comment, Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'content', ]


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['text']

blog/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.urls.base import reverse
from blog.forms import CommentForm, PostForm
from blog.models import Comment, Post
from django.shortcuts import get_object_or_404, render

# Create your views here.
from resumes.views import owner

from django.db.models import Q


def blog_home(request):
    return render(request, 'blog/blog_home.html')


class PostListView(owner.OwnerListView):
    """ Post List Page/View """
    model = Post
    ordering = ['-updated_at']
    queryset = Post.objects.filter(status=Post.STATUS_APPROVED)

    def get_queryset(self):
        base_queryset = super(PostListView, self).get_queryset()

        searchTerm = self.request.GET.get("search", False)
        if searchTerm:
            query_title_and_text = Q(title__icontains=searchTerm) | Q(content__icontains=searchTerm)
            res_queryset = base_queryset.filter(query_title_and_text)
        else:
            res_queryset = base_queryset

        return res_queryset


class PostDetailView(owner.ParentOwnerDetailView):
    """ Post Detail Page/View """
    model = Post
    queryset = Post.objects.filter(status=Post.STATUS_APPROVED)
    child_model = Comment
    child_form = CommentForm

    # The ParentOwnerDetailView do all of this in an OOP manner:
    # def get_context_data(self, **kwargs):
    #     context = super(PostDetailView, self).get_context_data(**kwargs)
    #     # Getting the specific Post Item
    #     pk = self.kwargs['pk']
    #     PostQuery = get_object_or_404(Post, id=pk)
    #     # Get all the existing Comments for the post
    #     comments = Comment.objects.filter(post=PostQuery).order_by('-updated_at')
    #     comment_form = CommentForm()
    #     print(f'typeof: {type(comment_form)}')
    #     print(f'dict: {comment_form.instance.__dict__}')
    #     context = {'post': PostQuery, 'comments': comments, 'comment_form': comment_form}
    #     return context


class PostCreateView(owner.OwnerCreateView):
    """ Post Create Page/View """
    model = Post
    form_class = PostForm


class PostUpdateView(owner.OwnerUpdateView, UserPassesTestMixin):
    """ Post Update Page/View (with TestMixin)"""
    model = Post
    queryset = Post.objects.filter(status=Post.STATUS_APPROVED)
    form_class = PostForm

    def test_func(self) -> bool:
        post_author = self.get_object().author
        if self.request.user == post_author:
            return True
        return False

    def get_success_url(self):
        # print("PostUpdateView:get_success_url")
        # print(f'pk is: {self.kwargs.get("pk")}')
        return reverse('blog:post_detail', args=[self.kwargs.get('pk')])


class PostDeleteView(owner.OwnerDeleteView):
    """ Post Delete Page/View """
    model = Post


# ## Comment Views


class CommentCreateView(owner.ChildOwnerCreateView):
    """ Comment Create Page/View """
    model = Comment
    form_class = CommentForm

    parent_model = Post
    parent_reverse_prefix = 'blog:post_detail'

    # The ChildOwnercreate do all of this in an OOP manner:
    # We got an error ('IntegrityError at /blog/post/2/create_comment/')
    # i.e: django cant find the post on which the user want to comment on..
    # def form_valid(self, form):
    #    try:
    #        post_pk = self.kwargs.get('pk', None)
    #        self.success_url=reverse_lazy(f'blog:post_detail', args=[post_pk])
    #        currentPost = get_object_or_404(Post, id=post_pk)
    #        form.instance.post = currentPost
    #    except Exception as e:
    #        print("==============")
    #        print(e, type(e))
    #        print("==============")
    #    return super(CommentCreateView, self).form_valid(form)

    # def get_success_url(self):
    #    try:
    #        url = reverse('blog:post_detail', args=[self.parent_pk])
    #    except:
    #        print("self.parent_pk is not defined")
    #        url = super(CommentCreateView, self).get_success_url()
    #    finally:
    #        return url


class CommentDetailView(owner.OwnerDetailView):
    """ Comment Detail Page/View """
    model = Comment


class CommentUpdateView(owner.OwnerUpdateView):
    """ Comment Update Page/View """
    model = Comment
    fields = ['text']

    def get_success_url(self):
        # print("CommentUpdateView:get_success_url", f'pk is: {self.kwargs.get('pk')}')
        # print("parent pk is:", self.__dict__)
        return reverse('blog:post_detail', args=[self.object.post_id])


class CommentDeleteView(owner.OwnerDeleteView):
    """ Comment Delete Page/View """
    model = Comment

    def get_success_url(self):
        return reverse('blog:post_detail', args=[self.object.post_id])

blog/templates/blog/blog_home.html
{% extends "base.html" %}
<!-- Load crispy form -->
{% load crispy_forms_tags %} 
{% block content %}

    <div class="content-section">
        <h2>Hi</h2>

        <ol>
            
            <li><a href="{% url 'blog:post_list' %}">Post list</a></li>
            <li><a href="{% url 'blog:post_create' %}">Post create</a></li>
            <li><a href="{% url 'blog:post_detail' 1 %}">Post detail</a></li>
            <li><a href="{% url 'blog:post_update' 1 %}">Post update</a></li>
            <li><a href="{% url 'blog:post_delete' 1 %}">Post delete</a></li>
        </ol>


        <ol>
            
            <li><a href="{% url 'resumes:review_list' %}">Review list</a></li>
            <li><a href="{% url 'resumes:review_create' 1 %}">Review create</a></li>
            <li><a href="{% url 'resumes:review_detail' 1 %}">Review detail</a></li>
            <li><a href="{% url 'resumes:review_update' 1 %}">Review update</a></li>
            <li><a href="{% url 'resumes:review_delete' 1 %}">Review delete</a></li>
        </ol>
        
    </div>
{% endblock content %}

blog/templates/blog/comment_confirm_delete.html
{% extends "base.html" %}


{% block content %}
    <h2>comment_confirm_delete</h2>
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ comment }}"?</p>
        <input type="submit" value="Confirm">
    </form>

{% endblock content %}

blog/templates/blog/comment_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <h2>comment_form</h2>

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Save">
    </form>

{% endblock content %}

blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}


{% block content %}
    <h2>post_confirm_delete</h2>
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ post.title }}"?</p>
        <input type="submit" value="Confirm">
    </form>

{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}


{% block content %}
    <div class="card m-2 overflow-hidden">

		<div class="card-header">
			<div class="d-flex bd-highlight align-items-start">
				<img class="rounded-circle img-thumbnail center card-img-start" src="{{ post.author.profile.image.url }}" alt=" ">
					
				<div class="align-self-start flex-fill">
                    <div class="align-self-start-inner d-flex">
					    <span class="me-auto" style="margin-top: auto;">
						    <a class="card-user-link" href="{ % url 'blog:user_posts' post.author.username %}">{{ post.author }}</a>
		      			    <!-- Format the date: -->
		      			    <small class="text-muted">{{ post.created_at|date:"F d, Y" }}</small>
                            <small class="text-muted"> ({{ post.updated_at|date:"F d, Y" }})</small>
		      			    <!-- https://docs.djangoproject.com/en/2.0/ref/templates/builtins/#date -->
                        </span>

                        <!-- Not protect, just do not display! -->
                        {% if post.author == user %}
	      		        <span class="ms-auto">
	      			        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'blog:post_update' post.id %}">Update Post</a>
	      			        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'blog:post_delete' post.id %}">Delete Post</a>
                        </span>
	      	            {% endif %}
                    </div>
		      		
		      		<h5 class="card-title align-self-end">
		    			<a class="card-title" href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a>
		    		</h5>
		    	</div>
			</div>
				
		</div>

		<div class="card-body">
            <!-- 16:9 aspect ratio -->
            <div class="ratio ratio-1x1 p-1" style="margin-left: auto; margin-right: auto; width: 90%; height: 75vh/*950px*/;">
                <p class="card-text">{{ post.content }}</p>
            </div>
            <!-- https://getbootstrap.com/docs/5.0/helpers/ratio/ -->

            <hr/>
            
		</div>
        <div class="card-footer">
            {% comment "optional button" %}
            {% if resume.tags.all %}
                Tags:
            {% endif %}
            {% for tag in resume.tags.all %}
                <span class="badge bg-info rounded-pill text-dark">{{ tag.name }}</span>
            {% endfor %}
            {% endcomment %}

        </div>
	</div>

    <div class="container">
        {% if post.comment_set %}
            {% for comment in post.comment_set.all %}
                <div class="card m-2">
                    <div class="card-header d-flex">
                        <div class="me-auto">
                            <a class="card-user-link" href="{ % url 'blog:user_comments' comment.author.username %}">{{ comment.author }}</a>
                            <small class="text-muted">{{ comment.created_at|date:"F d, Y" }}</small>
                        </div>
                        
                        {% if comment.author == user %}
	      		            <div class="ms-auto">
	      			            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'blog:comment_update' comment.id %}">Edit</a>
	      			            <a class="btn btn-warning btn-sm mt-1 mb-1" href="{% url 'blog:comment_delete' comment.id %}">Delete</a>
	      		            </div>
	      	            {% endif %}
                    </div>

                    <div class="card-body d-flex">
                        <span class="me-auto">text:{{ comment.text }}</span>
                        
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>

    <div>
        
        <br>
        {% load crispy_forms_tags %}
        <form action="{% url 'blog:comment_create' post.id %}" method="post" class="p-2 m-2">
            {% csrf_token %}
            Comment Form
            <div class="row">
                <div class="col-10 mb-0">{{ comment_form.text|as_crispy_field }}</div>
            </div>
            <div class="d-grid justify-content-end">
                <input type="submit" value="Save" class="btn btn-primary">
            </div>
            
        </form>

    </div>

{% endblock content %}

blog/templates/blog/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <h2>post_form</h2>

    <!-- fixed with the help of: -->
    <!-- https://stackoverflow.com/a/32429092/3790620 -->
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Save">
    </form>

{% endblock content %}

blog/templates/blog/post_list.html
{% extends "base.html" %}

{% block content %}
    {% if post_list %}
        <div class="cardgroup">
            {% for post in post_list %}
            <!-- TODO: Consider to use AJAX to request the post html from another view. -->
                <div class="card m-2 overflow-hidden">
                    <div class="card-header">
                        <div class="d-flex bd-highlight align-items-start">
                            <img class="rounded-circle img-thumbnail center card-img-start" src="{{ post.author.profile.image.url }}" alt=" ">
                                
                            <div class="align-self-start flex-fill"><!-- card-user-start -->
                                <div class="align-self-start-inner">
                                    <a id="name" class="card-user-link" href="{% url 'blog:user_posts' post.author.username }">{{ post.author }}</a>
                                      <!-- Format the date: -->
                                      <small class="text-muted">created_at: {{ post.created_at|date:"F d, Y" }}</small>
                                      <small class="text-muted">updated_at: {{ post.updated_at|date:"F d, Y" }}</small>
                                      <!-- https://docs.djangoproject.com/en/2.0/ref/templates/builtins/#date -->
                                </div>
                                
                                
                                <h5 class="card-title align-self-end">
                                    <a class="card-title" href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a>
                                </h5>
                            </div>
                        </div>
                            
                    </div>

                    <div class="card-body">
                        
                        <!-- 16:9 aspect ratio -->
                        <div class="ratio ratio-1x1" style="margin-left: auto; margin-right: auto; width: 90%; height: 75vh/*950px*/;">
                            <p class="card-text">{{ post.content }}</p>
                        </div>
                        <!-- https://getbootstrap.com/docs/5.0/helpers/ratio/ -->
                        
                    </div>
                    <div class="card-footer">
                        {% comment "optional button" %}
                        {% if resume.tags.all %}
                            Tags:
                        {% endif %}
                        {% for tag in resume.tags.all %}
                            <span class="badge bg-info rounded-pill text-dark">{{ tag.name }}</span>
                        {% endfor %}
                        {% endcomment %}

                    </div>

                </div>
                
            {% endfor %}

        </div>

        <br>

    {% else %}
        <strong>No Posts was found</strong>
    {% endif %}
    
{% endblock content %}

{% block js %}
    <script type="text/javascript">
        function changeSearchHolder()
        {
            search_input = document.getElementsByName('search')[0];
            search_input.placeholder = 'Search Posts..';
        }
        changeSearchHolder();
    </script>
{% endblock js %}