accounts/urls.py
from django.urls import path
from .views import register, profile

app_name = "accounts"

urlpatterns = [
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
]

blog/urls.py
from django.urls import path
from django.urls.base import reverse_lazy
from . import views

app_name = "blog"
urlpatterns = [
    path('', views.blog_home, name="blog_home"),

    # Posts CRUD
    path('list/', views.PostListView.as_view(), name="post_list"),
    path('post/create/', views.PostCreateView.as_view(success_url=reverse_lazy(f'{app_name}:post_list')), name="post_create"),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name="post_detail"),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name="post_update"),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(success_url=reverse_lazy(f'{app_name}:post_list')), name="post_delete"),

    # Comments CRUD
    path('post/<int:pk>/create_comment/', views.CommentCreateView.as_view(success_url=reverse_lazy(f'{app_name}:post_list')), name="comment_create"),
    path('comment/<int:pk>/', views.CommentDetailView.as_view(), name="comment_detail"),
    path('comment/<int:pk>/update/', views.CommentUpdateView.as_view(), name="comment_update"),
    path('comment/<int:pk>/delete/', views.CommentDeleteView.as_view(success_url=reverse_lazy(f'{app_name}:post_list')), name="comment_delete"),
]

resumes/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy

from . import views


from django.views.decorators.cache import cache_page

app_name = "resumes"
# cache_page(60*15)(view)

urlpatterns = [

    path('', cache_page(60*15, key_prefix="resume_list")(views.home), name="home"),

    # Resumes CRUD
    # path('list/', (views.ResumeListView.as_view()), name="resume_list"),
    path('list/', views.ResumeListView.as_view(), name="resume_list"),
    path('user/<str:username>/', views.UserResumeListView.as_view(), name="user_resumes"),
    path('resume/create/', views.ResumeCreateView.as_view(success_url=reverse_lazy(f'{app_name}:resume_list')), name="resume_create"),
    path('resume/<int:pk>/', views.ResumeDetailView.as_view(), name="resume_detail"),
    path('resume/<int:pk>/update/', views.ResumeUpdateView.as_view(), name="resume_update"),
    path('resume/<int:pk>/delete/', views.ResumeDeleteView.as_view(success_url=reverse_lazy(f'{app_name}:resume_list')), name="resume_delete"),

    # ! path('resume/list/<int:pk>/', views.GetResume, name="get_resume"),

    # Reviews CRUD
    path('review/list/', views.ReviewListView.as_view(), name="review_list"),
    path('user/reviews/<str:username>/', views.UserReviewListView.as_view(), name="user_reviews"),
    path('resume/<int:pk>/create_review/', views.ReviewCreateView.as_view(), name="review_create"),
    path('review/<int:pk>/', views.ReviewDetailView.as_view(), name="review_detail"),
    path('review/<int:pk>/update/', views.ReviewUpdateView.as_view(), name="review_update"),
    path('review/<int:pk>/delete/', views.ReviewDeleteView.as_view(success_url=reverse_lazy(f'{app_name}:resume_list')), name="review_delete"),
]

templates/about.html
{% extends "base.html" %}
<!-- Load crispy form -->
{% load crispy_forms_tags %} 
{% block content %}

    <div class="content-section">
        <h2>About Page</h2>

        <p> 
            This site will have 3 apparent pieces:
            <ol>
                <li>The resume part, on which users can upload their resumes for others to review</li>
                <li>The Blog part, that allow users to create posts and publish it</li>
                <li>The ORM training part, on which one can practice his ORM knowledge (TODO)</li>
            </ol>

            There are parts that are not visible, like:
            <ol>
                <li>The account app which "shadows" the django.accounts default app</li>
                <li>The REST API for the resumes app, implemented with DRF</li>
                <li>The use of Django Caching (memcached), DJDT, Testing, Coverage and docker</li>
                <li>The N+1 Problems that was solved and optimized the App.</li>
                <li>This Project has 96% Test Coverage (Using Coverage)</li>
            </ol>
        </p>
        
    </div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<!-- https://youtu.be/qDwdMDQ8oX4 -->
<!-- https://getbootstrap.com/docs/4.0/getting-started/introduction/#starter-template -->
<!-- https://youtu.be/aHC3uTkT9r8 -->

<!-- Parent HTML Template -->
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link 
	href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" 
	rel="stylesheet" 
	integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" 
	crossorigin="anonymous">

	<!-- Bootstrap CSS -->
	<!-- load a static CSS file -->
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'resume_project/main.css' %}">
	{% block css %}{% endblock %}

	<!-- The title of the page -->
	{% if title %}
	<title>Django Site - {{ title }}</title>
	{% else %}
	<title>Django Site</title>
	{% endif %}
</head>

<body>
	<!--<h1> Blog Home </h1>-->

	<!-- The NavBar -->
	<header class="site-header">
		<nav class="navbar navbar-dark navbar-expand-lg bg-steel fixed-top">
			<div class="container-fluid">
				<!-- Branding -->
				<a class="navbar-brand mr-4" href="{ % url 'resumes:home' %}">Django Spot</a>

				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarToggle">
					<!-- Navbar Left Side -->
					<div class="navbar-nav me-auto">
						<a class="nav-item nav-link" href="#">Home</a>
						<a class="nav-item nav-link" href="{% url 'resumes:resume_list' %}">Resumes</a>
						<a class="nav-item nav-link" href="{% url 'blog:post_list' %}">Blog</a>
						<a class="nav-item nav-link" href="{% url 'site_about' %}">About</a>
					</div>

					<!-- Navbar Right Side -->
					<!-- Checks is a user is logged in or not and changed the left preview accordinglly -->
					<div class="navbar-nav ms-auto">
						{% if user.is_authenticated %} <!--Allow us to check if any user is currently logged in-->
						<li class="nav-item dropdown">
							<a href="#" class="nav-link dropdown-toggle" id="navbarDropdown_create" role="button" data-bs-toggle="dropdown" aria-expanded="false">
								Create
							</a>
							<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
								<li><a class="dropdown-item" href="{% url 'resumes:resume_create' %}">Create Resume</a></li>
								<li><hr class="dropdown-divider"></li>
								<li><a class="dropdown-item" href="{% url 'blog:post_create' %}">Create Post</a></li>
							</ul>
						</li>
						
						<a class="nav-item nav-link" href="{% url 'accounts:profile' %}">Profile</a>
						<a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
						{% else %}
						<a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
						<a class="nav-item nav-link" href="{% url 'accounts:register' %}">Register</a>
						{% endif %}
					</div>
				</div>
			</div>
		</nav>
	</header>

	<main role="main" class="container-fluid">
		<div class="row">
			<div class="col-md-8">
				<!-- Allow Messages display -->
				{% if messages %}
					{% for message in messages %}
						<div class="alert alert-{{ message.tags }}">{{ message.tags }} {{ message }}</div>
					{% endfor %}
				{% endif %}
				{% block content %}
				<!-- Allow child Template to put here child data -->
				{% endblock %}
			</div>

			<!-- Sidebar (in the right) -->
			<div class="col-md-4">
				<div class="container">
				<!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
					<div>
						<form id="FormSearch">
							<input type="text" placeholder="Search Resumes.." name="search"
							{% if search %} value="{{ search }}" {% endif %}>
							<button type="submit">Search</button>
						</form>
					</div>
					
				</div>
				
				<div class="content-section">
					<h3>Our Sidebar</h3>
					<p class='text-muted'>You can put any information here you'd like.
						<ul class="list-group">
							<li class="list-group-item list-group-item-light">Latest Posts</li>
							<li class="list-group-item list-group-item-light">Announcements</li>
							<li class="list-group-item list-group-item-light">Calendars</li>
							<li class="list-group-item list-group-item-light">etc</li>
						</ul>
					</p>
				</div>

				

				{ include "./empty.html" %}
			</div>

		</div>
		<div class="row m-3">
			{ include "./carousel.html" %}
		</div>
	</main>

	<!-- Bootstarp JS -->
	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->

	<!-- Version 5: Option 2: Separate Popper and Bootstrap JS -->
	<script 
	src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
	<script 
	src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>

	{% block js %}
	{% endblock %}

</body>
</html>