blog/urls.py
from django.urls import path
from django.urls.base import reverse_lazy
from . import views

app_name = "blog"
urlpatterns = [
    path('', views.blog_home, name="blog_home"),

    # Posts CRUD
    path('list/', views.PostListView.as_view(), name="post_list"),
    path('post/create/', views.PostCreateView.as_view(success_url=reverse_lazy(f'{app_name}:post_list')), name="post_create"),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name="post_detail"),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name="post_update"),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(success_url=reverse_lazy(f'{app_name}:post_list')), name="post_delete"),

    # Comments CRUD
    path('post/<int:pk>/create_comment/', views.CommentCreateView.as_view(success_url=reverse_lazy(f'{app_name}:post_list')), name="comment_create"),
    path('comment/<int:pk>/', views.CommentDetailView.as_view(), name="comment_detail"),
    path('comment/<int:pk>/update/', views.CommentUpdateView.as_view(), name="comment_update"),
    path('comment/<int:pk>/delete/', views.CommentDeleteView.as_view(success_url=reverse_lazy(f'{app_name}:post_list')), name="comment_delete"),
]

resumes/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy

from . import views


from django.views.decorators.cache import cache_page

app_name = "resumes"
# cache_page(60*15)(view)

urlpatterns = [

    path('', cache_page(60*15, key_prefix="resume_list")(views.home), name="home"),

    # Resumes CRUD
    # path('list/', (views.ResumeListView.as_view()), name="resume_list"),
    path('list/', views.ResumeListView.as_view(), name="resume_list"),
    path('user/<str:username>/', views.UserResumeListView.as_view(), name="user_resumes"),
    path('resume/create/', views.ResumeCreateView.as_view(success_url=reverse_lazy(f'{app_name}:resume_list')), name="resume_create"),
    path('resume/<int:pk>/', views.ResumeDetailView.as_view(), name="resume_detail"),
    path('resume/<int:pk>/update/', views.ResumeUpdateView.as_view(), name="resume_update"),
    path('resume/<int:pk>/delete/', views.ResumeDeleteView.as_view(success_url=reverse_lazy(f'{app_name}:resume_list')), name="resume_delete"),

    # ! path('resume/list/<int:pk>/', views.GetResume, name="get_resume"),

    # Reviews CRUD
    path('review/list/', views.ReviewListView.as_view(), name="review_list"),
    path('user/reviews/<str:username>/', views.UserReviewListView.as_view(), name="user_reviews"),
    path('resume/<int:pk>/create_review/', views.ReviewCreateView.as_view(), name="review_create"),
    path('review/<int:pk>/', views.ReviewDetailView.as_view(), name="review_detail"),
    path('review/<int:pk>/update/', views.ReviewUpdateView.as_view(), name="review_update"),
    path('review/<int:pk>/delete/', views.ReviewDeleteView.as_view(success_url=reverse_lazy(f'{app_name}:resume_list')), name="review_delete"),
]

resumes/models.py
from accounts.models import CustomUser
import re
from typing import List
from django.db import models
from django.db.models.aggregates import Count
from django.db.models.functions.text import Lower
from django.db.models.query_utils import Q
from django.urls.base import reverse
from django.utils import timezone
from django.conf import settings
import os
from django.core.cache import cache

# Create your models here.


class ResumeQuerySet(models.QuerySet):
    # Make a query method, that return any resume that belong any Tag from the given list

    def filter_by_tags(self, tags_id: List):
        """Filter by a given list of Tags id's"""
        return self.filter(tags__in=tags_id)

    # add a field of how many tags has any resume
    def score_tags(self):
        """
        Add a field 'score', which summerize how many tags each resume has.
        """
        return self.annotate(score=Count('tags'))

    # add a field of how many tags has any resume (from a given tags list)
    def score_tags_by_list(self, tags_id: List):
        """
        Add a field 'score', which summerize how many tags from the tags_id list each resume has.
        """
        Q_query = Q(tags__in=tags_id)
        return self.annotate(score=Count('tags', filter=Q_query))

    def fetch_store_resume_list(self):
        '''
        Used for Fetch and Store the query of all the resumes with the related fields.
        Used primarily by the 'ResumeListView' View.
        '''
        resumes_cache_key = "resumes"
        resumes_queryset = cache.get(resumes_cache_key)
        if resumes_queryset is None:
            resumes_queryset = self
            cache.set(resumes_cache_key, resumes_queryset, timeout=300)

        return resumes_queryset


    def filter_by_user_orderby_fetch(self, io_customUser: CustomUser, order_fields: List, fetch_fields: List):
        '''
        Filter Resumes by given "CustomUser", order by "order_fields" and fetching the "fetch_fields"
        Saves the Query in the cache for 300 seconds
        Return the wanted QuerySet.
        '''
        # get the resumes QuerySet of the user, Using low level caching
        user_resumes_key = str(io_customUser.username + "_resumes")
        resumes_queryset = cache.get(user_resumes_key)
        if resumes_queryset is None:
            resumes_queryset = self.filter(author=io_customUser).order_by(*order_fields).prefetch_related(*fetch_fields)
            cache.set(user_resumes_key, resumes_queryset, timeout=300)

        # resumes_queryset = self.filter(author=io_customUser).order_by(*order_fields).prefetch_related(*fetch_fields)
        return resumes_queryset


class Resume(models.Model):
    """Resume Model"""

    resume_file = models.FileField(upload_to='uploads/resumes/')
    text = models.TextField(default="")
    tags = models.ManyToManyField('Tag', blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    objects = ResumeQuerySet.as_manager()

    @property
    def filename(self):
        return os.path.basename(self.resume_file.name)

    def __str__(self):
        return f'{self.resume_file.name} File'

    def get_absolute_url(self):
        return reverse('resumes:resume_detail', kwargs={'pk': self.pk})


class Review(models.Model):
    """Review Model"""

    CHOICES = [(i, i) for i in range(11)]
    grade = models.IntegerField(choices=CHOICES)

    text = models.TextField(default="")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.author} review for {self.resume.filename} Resume'


class TagQuerySet(models.QuerySet):

    def lower_cased_name(self):
        '''Will Add a 'lower_name' field'''
        return self.annotate(lower_name=Lower('name'))

    def filter_by_lower_name(self, lower_names: List):
        return self.filter(lower_name__in=lower_names)

    def tags_id_from_str(self, searchTerm: str):
        '''Will return all tags id's that their names is in the given string'''
        # Find all existing tags
        exists_tags = self.lower_cased_name()

        # # Cache It (Get the e_t_l_n from the cached if exists there)
        e_t_l_n_key = str("resumes_tags_cache")
        existing_tags_lower_name = cache.get(e_t_l_n_key)
        if existing_tags_lower_name is None:
            # Find all existing tags names (in lower case)
            existing_tags_lower_name = exists_tags.values_list('lower_name', flat=True)
            cache.set(e_t_l_n_key, existing_tags_lower_name, timeout=60*60*24)

        # existing_tags_lower_name = exists_tags.values_list('lower_name', flat=True)

        # Build a REGEX to help find the tags names that is in the search string
        look_for = "|".join(f'\\b{p}\\b' for p in existing_tags_lower_name)

        # find all expressions from the search string
        required_tags_lower_name = re.findall(look_for, searchTerm.lower())

        # Find the Tags instances themselves
        tags_required = exists_tags.filter_by_lower_name(required_tags_lower_name).values_list('id', flat=True)

        return tags_required


class Tag(models.Model):
    """Tag Model (been added after the initial db design)"""
    name = models.CharField(max_length=25)

    objects = TagQuerySet.as_manager()

    def __repr__(self):
        return f'{self.name} (id:{self.pk})'

    def __str__(self):
        return f'{self.name}'

resumes/forms.py
# Create a Resume Form
# Create a Review Form


from django import forms
from resumes.models import Resume, Review


class ResumeForm(forms.ModelForm):

    class Meta:
        model = Resume
        fields = ['resume_file', 'text', 'tags']


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ['grade', 'text']

resumes/views/owner.py
from django.db.models.query_utils import Q
from django.shortcuts import get_object_or_404
from django.urls.base import reverse
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView

from django.contrib.auth.mixins import LoginRequiredMixin


class OwnerListView(ListView):
    """
    Sub-class the ListView to pass the request to the form.
    """


class OwnerDetailView(DetailView):
    """
    Sub-class the DetailView to pass the request to the form.
    """


class ParentOwnerDetailView(OwnerDetailView):
    """
    Sub-class of OwnerDetailView, that designed for handling a model with
    child model in the context_data.
    Parent view with its child model form, in the context.
    """
    child_model = None
    child_form = None
    child_queryset = None

    def get_context_data(self, **kwargs):
        context = super(ParentOwnerDetailView, self).get_context_data(**kwargs)

        # Getting the specific Parent Item
        pk = self.kwargs['pk']
        ParentQuery = get_object_or_404(self.model, id=pk)

        # Get all the existing Childs of the Parent
        if self.child_queryset is None:
            qQuery = Q(**{f'{self.model._meta.verbose_name}': ParentQuery})
            childs = self.child_model.objects.filter(qQuery).order_by("-updated_at")
        else:
            childs = self.child_queryset

        # define context names
        parent_model_name = f'{self.model.__name__.lower()}'
        childs_plural_name = f'{self.child_model._meta.verbose_name_plural}'
        child_form_verbose_name = f'{self.child_model._meta.verbose_name}_form'
        # init the child form
        child_form_empty_init = self.child_form()

        context = {
            f'{parent_model_name}': ParentQuery,
            f'{childs_plural_name}': childs,
            f'{child_form_verbose_name}': child_form_empty_init}

        return context


class OwnerCreateView(LoginRequiredMixin, CreateView):
    """
    Sub-class of the CreateView to automatically pass the Request to the Form
    and add the owner to the saved object.
    """

    # https://stackoverflow.com/questions/21652073/django-how-to-set-a-hidden-field-on-a-generic-create-view
    # https://stackoverflow.com/questions/19051830/a-better-way-of-setting-values-in-createview
    def form_valid(self, form):
        # print('OwnerCreateView:form_valid called')
        form.instance.author = self.request.user

        return super(OwnerCreateView, self).form_valid(form)


class ParentOwnerCreateView(OwnerCreateView):
    """
    Sub-class of the OwnerCreateView, that redirect to its own detailview(?)
    """
    pass


class ChildOwnerCreateView(OwnerCreateView):
    """
    Sub-class of OwnerCreateView, that abstract the logic of creating an
    object from the parent page/view.
    Associate the child item with correct parent pk.
    """

    # new class attributes, for parent association.
    parent_model = None
    parent_reverse_prefix = None
    parent_pk = None

    # override the 'form_valid' method
    def form_valid(self, form):
        try:
            self.parent_pk = self.kwargs.get('pk', None)
            currentParent = get_object_or_404(self.parent_model, id=self.parent_pk)

            # find the field from the type of the parent and popluate it
            setattr(form.instance, self.parent_model.__name__.lower(), currentParent)
        except Exception as e:
            print("ChildOwnerCreateView:form_valid:Exception:\n", e, type(e))

        return super(ChildOwnerCreateView, self).form_valid(form)

    # override the 'get_success_url' method
    def get_success_url(self):
        try:
            url = reverse(self.parent_reverse_prefix, args=[self.parent_pk])
        except Exception as e:
            print("self.parent_pk or parent_reverse_prefix are not defined")
            url = super(ChildOwnerCreateView, self).get_success_url()
        finally:
            return url


class OwnerUpdateView(LoginRequiredMixin, UpdateView):
    """
    Sub-class the UpdateView to pass the request to the form and limit the
    queryset to the requesting user.
    """

    def get_queryset(self):
        """ Limit a User to only modifying their own data. """
        # print('OwnerUpdateView:get_queryset called')

        qs = super(OwnerUpdateView, self).get_queryset()
        # qs <- Get the queryset of the model. 
        # QuerySet of all objects from the model, but it is filtered in 'get_object', using 'pk'.
        # The QuerySet is executed in 'get_object', using 'get' method (for one object only)

        return qs.filter(author=self.request.user)  # filter on 'author'.


class OwnerDeleteView(LoginRequiredMixin, DeleteView):
    """
    Sub-class the DeleteView to restrict a User from deleting other
    User's data.
    """

    def get_queryset(self):
        # print('OwnerDeleteView:get_queryset called')

        qs = super(OwnerDeleteView, self).get_queryset()
        return qs.filter(author=self.request.user)



# References

# https://docs.djangoproject.com/en/3.0/ref/class-based-views/mixins-editing/#django.views.generic.edit.ModelFormMixin.form_valid

# https://stackoverflow.com/questions/862522/django-populate-user-id-when-saving-a-model

# https://stackoverflow.com/a/15540149

# https://stackoverflow.com/questions/5531258/example-of-django-class-based-deleteview


# template names in:
# https://docs.djangoproject.com/en/3.1/topics/auth/default/#module-django.contrib.auth.views


# Mine
# read:
# https://stackoverflow.com/questions/18172102/object-ownership-validation-in-django-updateview
# One can check it, like described in:
# https://stackoverflow.com/questions/28775123/edit-and-replay-xhr-chrome-firefox-etc
# Or in
# https://stackoverflow.com/q/4797534/3790620

resumes/views/review_views.py
from django.shortcuts import get_object_or_404
# Create your views here.


from django.urls import reverse
from django.urls.base import reverse
from django.views.generic import ListView
from accounts.models import CustomUser

from resumes.models import Review, Resume
from .owner import OwnerListView, OwnerDetailView,\
     OwnerCreateView, OwnerUpdateView, OwnerDeleteView, ChildOwnerCreateView


class ReviewListView(OwnerListView):
    """ Review List Page/View """
    model = Review
    # By convention:
    # template_name = "resumes/<modelName>_list.html"


class UserReviewListView(ListView):
    """ Review User List Page/View """
    model = Review
    template_name = 'resumes/user_reviews.html'
    # context_object_name = 'reviews'

    def get_queryset(self):
        user = get_object_or_404(CustomUser, username=self.kwargs.get('username'))

        return Review.objects.filter(author=user).order_by('-id')


class ReviewDetailView(OwnerDetailView):
    """ Review Detail Page/View """
    model = Review
    # template_name = "resumes/<modelName>_detail.html"


class ReviewCreateView(ChildOwnerCreateView):
    """ Review Create Page/View """
    model = Review
    fields = ['grade', 'text']
    # template_name = "resumes/<modelName>_form.html"

    parent_model = Resume
    parent_reverse_prefix = 'resumes:resume_detail'

    # # The ChildOwnercreate do all of this in an OOP manner:
    # def form_valid(self, form):
    #     # print("ReviewCreateView:form_valid")
    #     # Define 2 ForeignKey(s) inside a createview
    #     # Example:
    #     #  form.instance.grade = self.request.POST.get('grade', None)
    #     # https://stackoverflow.com/a/53639341/3790620
    #     # Assign the parent object (ForeignKey) in the form
    #     try:
    #         resume_pk = self.kwargs.get('pk', None)
    #         self.success_url = reverse(f'resumes:resume_detail', args=[resume_pk])
    #         currentResume = get_object_or_404(Resume, id=resume_pk)
    #         # Calls get() on a given model manager,\
    #         #  but it raises Http404 instead of the model’s DoesNotExist exception.
    #         form.instance.resume = currentResume
    #     except Exception as e:
    #         print("ReviewCreateView:form_valid:Exception:\n", e, type(e))
    #     return super(ReviewCreateView, self).form_valid(form)


class ReviewUpdateView(OwnerUpdateView):
    """ Review Update Page/View """
    model = Review
    fields = ['grade', 'text']

    def get_success_url(self):
        # print("CommentUpdateView:get_success_url", f"pk is: {self.kwargs.get('pk')}")
        # print("parent pk is:", self.object.resume_id)
        return reverse('resumes:resume_detail', args=[self.object.resume_id])


class ReviewDeleteView(OwnerDeleteView):
    """ Review Delete Page/View """
    model = Review
    # template_name = "resumes/<modelName>_confirm_delete.html"

    def get_success_url(self):
        return reverse('resumes:resume_detail', args=[self.object.resume_id])

resumes/templates/resumes/home.html
{% extends "base.html" %}
<!-- Load crispy form -->
{% load crispy_forms_tags %} 
{% block content %}

    <div class="content-section">
        <h2>Hi</h2>

        <ol>
            
            <li><a href="{% url 'resumes:resume_list' %}">Resume list</a></li>
            <li><a href="{% url 'resumes:resume_create' %}">Resume create</a></li>
            <li><a href="{% url 'resumes:resume_detail' 1 %}">Resume detail</a></li>
            <li><a href="{% url 'resumes:resume_update' 1 %}">Resume update</a></li>
            <li><a href="{% url 'resumes:resume_delete' 1 %}">Resume delete</a></li>
        </ol>


        <ol>
            
            <li><a href="{% url 'resumes:review_list' %}">Review list</a></li>
            <li><a href="{% url 'resumes:review_create' 1 %}">Review create</a></li>
            <li><a href="{% url 'resumes:review_detail' 1 %}">Review detail</a></li>
            <li><a href="{% url 'resumes:review_update' 1 %}">Review update</a></li>
            <li><a href="{% url 'resumes:review_delete' 1 %}">Review delete</a></li>
        </ol>
        
    </div>
{% endblock content %}

resumes/templates/resumes/resume_confirm_delete.html
{% extends "base.html" %}


{% block content %}
    <h2>resume_confirm_delete</h2>
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ resume.filename }}"?</p>
        <input type="submit" value="Confirm">
    </form>

{% endblock content %}

resumes/templates/resumes/resume_detail.html
{% extends "base.html" %}


{% block content %}
    <h2>resume_detail</h2>
    <div class="card m-2 overflow-hidden">

		<div class="card-header">
			<div class="d-flex bd-highlight align-items-start">
				<img class="rounded-circle img-thumbnail center card-img-start" src="{{ resume.author.profile.image.url }}" alt=" ">
					
				<div class="align-self-start flex-fill">
                    <div class="align-self-start-inner d-flex">
					    <span class="me-auto" style="margin-top: auto;">
						    <a class="card-user-link" href="{% url 'resumes:user_resumes' resume.author.username %}">{{ resume.author }}</a>
		      			    <!-- Format the date: -->
		      			    <small class="text-muted">{{ resume.created_at|date:"F d, Y" }}</small>
		      			    <!-- https://docs.djangoproject.com/en/2.0/ref/templates/builtins/#date -->
                        </span>

                        <!-- Not protect, just do not display! -->
                        {% if resume.author == user %}
	      		        <span class="ms-auto">
	      			        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'resumes:resume_update' resume.id %}">Update Resume</a>
	      			        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'resumes:resume_delete' resume.id %}">Delete Resume</a>
                        </span>
	      	            {% endif %}
                    </div>
		      		
		      		<h5 class="card-title align-self-end">
		    			<a class="card-title" href="{% url 'resumes:resume_detail' resume.id %}">{{ resume.filename }}</a>
		    		</h5>
		    	</div>
			</div>
				
		</div>

		<div class="card-body">
            <!-- 16:9 aspect ratio -->
            <div class="ratio ratio-1x1 p-1" style="margin-left: auto; margin-right: auto; text-align: center; width: 90%; height: 75vh/*950px*/; background-color: rgb(82,86,89); border-bottom: solid;">
                <iframe class="embed-responsive-item" src="{{resume.resume_file.url}}"></iframe>
            </div>
            <!-- https://getbootstrap.com/docs/5.0/helpers/ratio/ -->

            <hr/>
            <p class="card-text">{{ resume.text }}**</p>

            
			
            {% comment "optional pdf" %}
            <!--
            <div id="adobe-dc-view" style="margin-left: auto; margin-right: auto; text-align: center; width: 90%; height: 75vh/*950px*/;"></div>
            <script src="https://documentcloud.adobe.com/view-sdk/main.js"></script>
            <script type="text/javascript">
                /*PDF Embed API */
                document.addEventListener("adobe_dc_view_sdk.ready", function()
                {
                    // bd7e8e14e5dd48dca607602e687a8a3f - django-02-files.s3.amazonaws.com
                    // a3b351c206d54bf680c0bd662a10e8d0 - localhost
                    var adobeDCView = new AdobeDC.View({clientId: "a3b351c206d54bf680c0bd662a10e8d0", divId: "adobe-dc-view"});
                    adobeDCView.previewFile(
                    {
                        //content:   {location: {url: "https://documentcloud.adobe.com/view-sdk-demo/PDFs/Bodea Brochure.pdf"}},
                        content:   {location: {url: "{{resume.resume_file.url}}"}},
                        metaData: {fileName: "{{ resume.author }} {{ resume.id }} resume "}
                    });

                    console.log(adobeDCView);
                    console.log("adobeDCView");
                });
                
                    // My Console:
                    // https://console.adobe.io/projects/541573/4566206088344631129/credentials/163239/details

                    // https://www.w3schools.com/cssref/css_units.asp
            </script>
            -->
            {% endcomment %}
		</div>
        <div class="card-footer">
            {% if resume.tags.all %}
                Tags:
            {% endif %}
            {% for tag in resume.tags.all %}
                <span class="badge bg-info rounded-pill text-dark">{{ tag.name }}</span>
            {% endfor %}

        </div>
	</div>

    <div class="container" id="div_reviews">
        {% if resume.review_set %}
            {% for review in resume.review_set.all %}
                <div class="card m-2">
                    <div class="card-header d-flex">
                        <div class="me-auto">
                            <a class="card-user-link" href="{% url 'resumes:user_reviews' review.author.username %}">{{ review.author }}</a>
                            <small class="text-muted">{{ review.created_at|date:"F d, Y" }}</small>
                        </div>
                        
                        {% if review.author == user %}
	      		            <div class="ms-auto">
	      			            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'resumes:review_update' review.id %}">Edit</a>
	      			            <a class="btn btn-warning btn-sm mt-1 mb-1" href="{% url 'resumes:review_delete' review.id %}">Delete</a>
	      		            </div>
	      	            {% endif %}
                    </div>

                    <div class="card-body d-flex">
                        <span class="me-auto">{{ review.text }}</span>
                        <span class="ms-auto"><span class="p-2 border rounded-circle border-info">grade:{{ review.grade }}</span></span>
                    </div>
                </div>
            {% empty %}
                <div class="card m-2">
                    <strong>No Reviews was found</strong>
                </div>
            {% endfor %}
        {% endif %}
    </div>

    <div>
        Review Form
        <br>
        {% load crispy_forms_tags %}
        <form action="{% url 'resumes:review_create' resume.id %}" method="post" class="p-2 m-2">
            {% csrf_token %}
            <div class="row">
                <div class="col-10 mb-0">{{ review_form.text|as_crispy_field }}</div>
                <div class="col-2 mb-0">{{ review_form.grade|as_crispy_field }}</div>
            </div>
            <div class="d-grid justify-content-end">
                <input type="submit" value="Save" class="btn btn-primary">
            </div>
            
        </form>

    </div>

{% endblock content %}

resumes/templates/resumes/review_detail.html
{% extends "base.html" %}


{% block content %}
    <h2>review_detail</h2>
    <div class="card m-2 overflow-hidden">

		<div class="card-header">
			<div class="d-flex bd-highlight align-items-start">
				<img class="rounded-circle img-thumbnail center card-img-start" src="{{ review.author.profile.image.url }}" alt=" ">
					
				<div class="align-self-start flex-fill">
					<div class="align-self-start-inner d-flex">
					<span class="me-auto" style="margin-top: auto;">
						<a class="card-user-link" href="{% url 'resumes:user_reviews' review.author.username %}">{{ review.author }}</a>
		      			<!-- Format the date: -->
		      			<small class="text-muted">{{ review.created_at|date:"F d, Y" }}</small>
		      			<!-- https://docs.djangoproject.com/en/2.0/ref/templates/builtins/#date -->
					</span>


					
		      				
					{% if review.author == user %}
						<span class="ms-auto">
							<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'resumes:review_update' review.id %}">Update</a>
							<a class="btn btn-warning btn-sm mt-1 mb-1" href="{% url 'resumes:review_delete' review.id %}">Delete</a>
						</span>
					{% endif %}
					</div>

		      		<h5 class="card-title align-self-end">
		    			<a class="card-title" href="{% url 'resumes:review_detail' review.id %}">{{ review.author }} Review Of '{{ review.resume.filename }}'</a>
		    		</h5>
		    	</div>
			</div>
				
		</div>

		<div class="card-body d-flex">
			<span class="me-auto">text:{{ review.text }}</span>
			<span class="ms-auto"><span class="p-2 border rounded-circle border-info">grade:{{ review.grade }}</span></span>
			
		</div>

        <div class="card-footer">
            
            
        </div>

	</div>
{% endblock content %}

resumes/templates/resumes/user_reviews.html
{% extends "base.html" %}


{% block content %}
    <h2>user reviews</h2>
    <div class="container">

        {% if review_list %}
            <!-- TODO: Fix to something normal -->
            
            {% for review in review_list %}
            <div class="card m-2">
                <div class="card-header">
                    <div class="d-flex bd-highlight align-items-start">
                        <img class="rounded-circle img-thumbnail center card-img-start" src="{{ review.author.profile.image.url }}" alt=" ">
                            
                        <div class="align-content-start flex-fill">
                            <div class="align-self-start-inner d-flex">
                                <span class="me-auto" style="margin-top: auto;">
                                    <a class="card-user-link" href="{% url 'resumes:user_reviews' review.author.username %}">{{ review.author }}</a>
                                    <!-- Format the date: -->
                                    <small class="text-muted">{{ review.created_at|date:"F d, Y" }}</small>
                                    <!-- https://docs.djangoproject.com/en/2.0/ref/templates/builtins/#date -->
                                </span>
                                
                                <!-- Not protect, just do not display! -->
                                {% if review.author == user %}
                                <span class="ms-auto">
                                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'resumes:review_update' review.id %}">Edit</a>
                                    <a class="btn btn-warning btn-sm mt-1 mb-1" href="{% url 'resumes:review_delete' review.id %}">Delete</a>
                                </span>
                                {% endif %}
                                {% if user.is_authenticated %}
                                {% endif %}
                            </div>

                            <h5 class="card-title align-self-end">
                                <a class="card-title" href="{% url 'resumes:review_detail' review.id %}">{{ review.author }} Review Of '{{ review.resume.filename }}'</a>
                            </h5>
                        </div>
                        
                    </div>
                        
                </div>


                <div class="card-body d-flex">
                    <span class="me-auto">text:{{ review.text }}</span>
                    <span class="ms-auto"><span class="p-2 border rounded-circle border-info">grade:{{ review.grade }}</span></span>
                    
                </div>

            </div>
            {% endfor %}

            
        {% else %}
            <strong>No Reviews was found</strong>
        {% endif %}

    </div>


    <br>
    <!-- for debud -->
    <pre>{% filter force_escape %}{% debug %}{% endfilter %}</pre>



{% endblock %}